# Generated by Django 4.0 on 2022-01-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huml', models.FloatField()),
                ('humw', models.FloatField()),
                ('ulnal', models.FloatField()),
                ('ulnaw', models.FloatField()),
                ('feml', models.FloatField()),
                ('femw', models.FloatField()),
                ('tibl', models.FloatField()),
                ('tibw', models.FloatField()),
                ('tarl', models.FloatField()),
                ('tarw', models.FloatField()),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
