# Generated by Django 4.0 on 2022-01-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruit',
            new_name='Born',
        ),
    ]
