# Generated by Django 4.0 on 2022-01-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_fruit_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='born',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
