# Generated by Django 4.0 on 2022-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_born_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='born',
            name='feml',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='femw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='huml',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='humw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='tarl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='tarw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='tibl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='tibw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='ulnal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='born',
            name='ulnaw',
            field=models.FloatField(default=0),
        ),
    ]
