# Generated by Django 4.0 on 2022-01-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_born_feml_alter_born_femw_alter_born_huml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='born',
            name='feml',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='femw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='huml',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='humw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='tarl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='tarw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='tibl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='tibw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='ulnal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='born',
            name='ulnaw',
            field=models.FloatField(),
        ),
    ]
